# Generated by Django 5.1.6 on 2026-07-16 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.CharField(max_length=32)),
                ('operator', models.CharField(max_length=128)),
                ('origin_destination', models.CharField(max_length=64)),
                ('movement_type', models.CharField(choices=[('Arrival', 'Arrival'), ('Departure', 'Departure')], max_length=16)),
                ('initial_fuel_minutes', models.FloatField()),
                ('scheduled_time', models.DateTimeField()),
                ('queue_entry_time', models.DateTimeField(blank=True, null=True)),
                ('runway_assigned_time', models.DateTimeField(blank=True, null=True)),
                ('completion_time', models.DateTimeField(blank=True, null=True)),
                ('wait_minutes', models.FloatField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Diverted', 'Diverted'), ('Cancelled', 'Cancelled')], default='Pending', max_length=16)),
                ('was_success', models.BooleanField(blank=True, null=True)),
                ('final_priority_score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='Runway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=16, unique=True)),
                ('heading_degrees', models.PositiveIntegerField()),
                ('length_metres', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['identifier'],
            },
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Running', 'Running'), ('Complete', 'Complete'), ('Error', 'Error')], default='Pending', max_length=16)),
                ('arrival_rate_per_hour', models.PositiveIntegerField()),
                ('departure_rate_per_hour', models.PositiveIntegerField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('max_wait_minutes', models.PositiveIntegerField()),
                ('aircraft_speed_knots', models.PositiveIntegerField()),
                ('include_closures', models.BooleanField(default=False)),
                ('random_seed', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AircraftEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('LowFuel', 'Low Fuel'), ('FuelCritical', 'Fuel Critical'), ('MechanicalFailure', 'Mechanical Failure'), ('PassengerHealth', 'Passenger Health')], max_length=32)),
                ('occurred_at', models.DateTimeField()),
                ('priority_boost', models.IntegerField(default=0)),
                ('detail', models.TextField(blank=True, null=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.aircraft')),
            ],
            options={
                'ordering': ['occurred_at'],
            },
        ),
        migrations.AddField(
            model_name='aircraft',
            name='runway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aircraft', to='api.runway'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircraft', to='api.simulation'),
        ),
        migrations.CreateModel(
            name='SimulationRunway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operational_status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=16)),
                ('operating_mode', models.CharField(choices=[('ArrivalsOnly', 'Arrivals Only'), ('DeparturesOnly', 'Departures Only'), ('Mixed', 'Mixed')], max_length=16)),
                ('runway', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='simulation_runways', to='api.runway')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_runways', to='api.simulation')),
            ],
        ),
        migrations.CreateModel(
            name='SimulationRunwayEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('Closed', 'Closed'), ('Reopened', 'Reopened')], max_length=16)),
                ('occurred_at', models.DateTimeField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('simulation_runway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closure_events', to='api.simulationrunway')),
            ],
            options={
                'ordering': ['occurred_at'],
            },
        ),
        migrations.AddIndex(
            model_name='aircraft',
            index=models.Index(fields=['simulation', 'outcome'], name='api_aircraf_simulat_ef09eb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='simulationrunway',
            unique_together={('simulation', 'runway')},
        ),
    ]
