# Generated by Django 6.0.5 on 2026-07-21 13:29

from django.db import migrations, models


def forwards_remap_statuses(apps, schema_editor):
    """Old data only ever recorded a binary Open/Closed status. Closed rows
    predate reason-tracking, so they're remapped to the most generic closed
    reason rather than guessed at."""
    SimulationRunway = apps.get_model('api', 'SimulationRunway')
    SimulationRunway.objects.filter(operational_status='Open').update(
        operational_status='Available'
    )
    SimulationRunway.objects.filter(operational_status='Closed').update(
        operational_status='EquipmentFailure'
    )


def backwards_remap_statuses(apps, schema_editor):
    SimulationRunway = apps.get_model('api', 'SimulationRunway')
    SimulationRunway.objects.filter(operational_status='Available').update(
        operational_status='Open'
    )
    SimulationRunway.objects.filter(
        operational_status__in=['RunwayInspection', 'SnowClearance', 'EquipmentFailure']
    ).update(operational_status='Closed')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_seed_runways'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulationrunway',
            name='operational_status',
            field=models.CharField(choices=[('Available', 'Available'), ('RunwayInspection', 'Runway Inspection'), ('SnowClearance', 'Snow Clearance'), ('EquipmentFailure', 'Equipment Failure')], default='Available', max_length=16),
        ),
        migrations.RunPython(forwards_remap_statuses, backwards_remap_statuses),
    ]
