# Generated by Django 5.1.6 on 2026-07-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_more_runways'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='cancel_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Running', 'Running'), ('Complete', 'Complete'), ('Error', 'Error'), ('Cancelled', 'Cancelled')], default='Pending', max_length=16),
        ),
    ]
