# Generated by Django 5.1.6 on 2026-07-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_simulationbatch_simulation_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationbatch',
            name='swept_variable',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
