# Generated by Django 5.1.6 on 2026-07-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_simulationbatch_swept_variable'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='last_heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
