# Generated by Django 5.1.6 on 2026-07-31 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_simulation_weather_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('arrival_rate_per_hour', models.PositiveIntegerField()),
                ('departure_rate_per_hour', models.PositiveIntegerField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('max_wait_minutes', models.PositiveIntegerField()),
                ('aircraft_speed_knots', models.PositiveIntegerField()),
                ('include_closures', models.BooleanField(default=False)),
                ('random_seed', models.IntegerField(blank=True, null=True)),
                ('weather_condition', models.CharField(choices=[('Clear', 'Clear (VMC)'), ('Windy', 'Windy'), ('Snow', 'Snow'), ('LowVisibility', 'Low Visibility (IMC)')], default='Clear', max_length=16)),
                ('heavy_percentage', models.PositiveIntegerField(blank=True, null=True)),
                ('medium_percentage', models.PositiveIntegerField(blank=True, null=True)),
                ('light_percentage', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateRunway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_mode', models.CharField(choices=[('ArrivalsOnly', 'Arrivals Only'), ('DeparturesOnly', 'Departures Only'), ('Mixed', 'Mixed')], max_length=16)),
                ('operational_status', models.CharField(choices=[('Available', 'Available'), ('RunwayInspection', 'Runway Inspection'), ('SnowClearance', 'Snow Clearance'), ('EquipmentFailure', 'Equipment Failure')], default='Available', max_length=16)),
                ('runway', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_runways', to='api.runway')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runways', to='api.template')),
            ],
            options={
                'unique_together': {('template', 'runway')},
            },
        ),
    ]
