# Generated by Django 5.1.6 on 2026-07-31 14:03

import api.models.simulation_share_link
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_simulation_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=api.models.simulation_share_link._generate_token, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('simulation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='share_link', to='api.simulation')),
            ],
        ),
    ]
