# Generated by Django 5.1.6 on 2026-08-03 14:29

import api.models.share_link_token
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_simulationsharelink'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompareShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulation_ids', models.JSONField()),
                ('token', models.CharField(default=api.models.share_link_token.generate_share_token, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SimulationBatchShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=api.models.share_link_token.generate_share_token, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='share_link', to='api.simulationbatch')),
            ],
        ),
    ]
